/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/AppProvider.vue')['default']
    ButoonIcon: typeof import('../components/custom/ButtonIcon.vue')['default']
    ButtonIcon: typeof import('./../components/custom/ButtonIcon.vue')['default']
    ExceptionBase: typeof import('./../components/common/ExceptionBase.vue')['default']
    FullScreen: typeof import('./../components/common/FullScreen.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconLocalAlova: typeof import('~icons/local/alova')['default']
    IconLocalBanner: typeof import('~icons/local/banner')['default']
    IconLocalVue: typeof import('~icons/local/vue')['default']
    IconPiker: typeof import('./../components/common/IconPiker.vue')['default']
    LangSwitch: typeof import('./../components/common/LangSwitch.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGIcon: typeof import('./../components/custom/SVGIcon.vue')['default']
    TableColumnSetting: typeof import('./../components/common/table/tableColumnSetting.vue')['default']
    TableHeaderOperation: typeof import('./../components/common/table/tableHeaderOperation.vue')['default']
    ThemeSwitch: typeof import('./../components/common/ThemeSwitch.vue')['default']
  }
}
