/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/common/403/': RouteRecordInfo<'/common/403/', '/common/403', Record<never, never>, Record<never, never>>,
    '/common/404/': RouteRecordInfo<'/common/404/', '/common/404', Record<never, never>, Record<never, never>>,
    '/common/500/': RouteRecordInfo<'/common/500/', '/common/500', Record<never, never>, Record<never, never>>,
    '/common/home/': RouteRecordInfo<'/common/home/', '/common/home', Record<never, never>, Record<never, never>>,
    '/common/iframe-page/[url]': RouteRecordInfo<'/common/iframe-page/[url]', '/common/iframe-page/:url', { url: ParamValue<true> }, { url: ParamValue<false> }>,
    '/common/login/': RouteRecordInfo<'/common/login/', '/common/login', Record<never, never>, Record<never, never>>,
    '/common/login/LoginRegisterForm': RouteRecordInfo<'/common/login/LoginRegisterForm', '/common/login/LoginRegisterForm', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/system/': RouteRecordInfo<'/system/', '/system', Record<never, never>, Record<never, never>>,
    '/system/menu/': RouteRecordInfo<'/system/menu/', '/system/menu', Record<never, never>, Record<never, never>>,
    '/system/menu/_MenuSaveOrUpdate': RouteRecordInfo<'/system/menu/_MenuSaveOrUpdate', '/system/menu/_MenuSaveOrUpdate', Record<never, never>, Record<never, never>>,
    '/system/role/': RouteRecordInfo<'/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/user/': RouteRecordInfo<'/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
  }
}
